*** TeX, LaTeX and document-processing
    TeX processes layout. LaTeX processes content. LaTeX has a collection of TeX
    macros and a program to process LaTeX documents, and because the plain TeX
    formatting commands are elementary, it provides ready-made commands for
    formatting and layout requirements e.g. chapter headings, footnotes,
    cross-references, bibliographies.

- `\usepackage[T1]{fontenc}`: output oriented, i.e. what fonts to use for
  printing characters.

- `\usepackage[utf8x]{inputenc}`: allows to input accented characters directly
  from the keyboard.

*** Numeric tower - numbers:
    Natural ℕ ⊆ Integer ℤ ⊆ Rational ℚ ⊆ Real ℝ ⊆ Complex ℂ ⊆ Quaternion ℍ

*** Structure type - record datatype composing a number of fields
    Sum type (OCaml): Generalization of enumeration. Bring heterogeneous values
    together into a common type

    (OCaml) type export: concrete / abstract - for fine-grained data encapsulation
    control

    Concrete export - full type definition remains known: so, clients of the modules
    can build or examine values of this type.

    Abstract export - only the type name is known outside the module. It then
    becomes impossible, from the outside, to create or inspect values of this type.

*** Pattern matching
- generalize the traditional case analysis construct
- examine and name data simultaneously

*** CLOS-based object orientation
    CommonLisp Object System

*** Foreign Function Interface FFI a.k.a. Language bindings
    Usage of different languages in one program;
    e.g. Java Native Interface JNI / Java Native Access JNA; extern "C"

*** TODO delimited continuations
*** TODO module system / OCaml
*** TODO hygienic macros
*** TODO multiple values
*** TODO threads

*** WSL
    Windows Subsystem for Linux 2 (WSL 2)

*** Data structures (are / do):
- static (Algorithms - dynamic)
- reasoning by an induction: consider the base case(s) and the general.
- remove the notion of time. Change over time is one of the major sources of
  program complexity.
- declarative. Most of the algorithms are imperative. Under declarative approach
  you don't have to trace the flow of time through a data structure.

*** Database
    Database schema         - Category
    Database instance       - Set-valued functor
    Database transformation - Universal Construction

*** Mixin in OOP
    A class with methods for use by another classes without having to be the
    parent class of these other classes.

    Mixin class is being "included" rather than "Inherited".

*** Lisp / Minimal Scheme Implementation for use as an Extension Language
    http://synthcode.com/wiki/chibi-scheme

    Scheme implementation meant to be embedded in a C-program, i.e. scripting
    C-applications etc.

    System Crafters Live! - Lisp Compiler Progress • Live Lisp Hacking • Q&A
    https://youtu.be/E-g3Ls1GRz4
