# generate pdf: M-x org-latex-export-to-pdf

#+LATEX_HEADER: \usepackage{cat-7-sketches}
# #+LATEX_HEADER: \usepackage{foo}

# https://en.wikipedia.org/wiki/List_of_mathematical_symbols_by_subject
# latexpreview / nolatexpreview C-c C-x C-l
# #+STARTUP: nolatexpreview
#+STARTUP: showeverything inlineimages latexpreview

Classes of math structures http://math.chapman.edu/~jipsen/structures/doku.php/

https://en.wikipedia.org/wiki/Algebraic_structure

* Algebraic structures
** Group-like structures
| Group-like-Structure | Closed | Associative | Identity | Invertibile | Commutative |
|----------------------|--------|-------------|----------|-------------|-------------|
| Semigroupoid         | -      | Y           | -        | -           | -           |
| Small-Category       | -      | Y           | Y        | -           | -           |
| Groupoid             | -      | Y           | Y        | Y           | -           |
| Magma                | Y      | -           | -        | -           | -           |
| Quasigroup           | Y      | -           | -        | Y           | -           |
| Loop                 | Y      | -           | Y        | Y           | -           |
| Semigroup            | Y      | Y           | -        | -           | -           |
| Inverse-Semigroup    | Y      | Y           | -        | Y           | -           |
| Monoid               | Y      | Y           | Y        | -           | -           |
| Group                | Y      | Y           | Y        | Y           | -           |
| Abelian-group        | Y      | Y           | Y        | Y           | Y           |

*** Semigroup / Halbgruppe $(G, \cdot)$:
    $\cdot$ is closed / closure: $a \cdot b$ must be also in $G$ \\
    Not required: $\cdot$ is commutative: $x \cdot y = y \cdot x$ \\
    $\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
    Not required: $e$ is neutral element (identity) \\
    Not required: x-inverse (dual obj): $x \cdot x\inv = x\inv \cdot x = e$

*** Monoid $(G, \cdot, e)$: A category of /many/ morphisms and /few/ (only one) objs in $G$
    Group w/o inverse elements \\
    $\cdot$ is closed / closure: $a \cdot b$ must be also in $G$ \\
    $\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
    $e$ is neutral element (identity) \\
    Not required: x-inverse (dual obj): $x \cdot x\inv = x\inv \cdot x = e$

*** Group $(G, \cdot, e)$:
    A Category w/ one object => every morphism is an isomorphism \\
    $\cdot$ is closed / closure: $a \cdot b$ must be also in $G$ \\
    Not required: $\cdot$ is commutative: $x \cdot y = y \cdot x$ \\
    $\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
    $e$ is neutral element (identity) \\
    x-inverse (dual obj): $x \cdot x\inv = x\inv \cdot x = e$ \\

*** Cyclic Group: generated by one element.

*** Commutative / Abelian group $(G, \cdot, e)$: Elems with multiplication
    Formalization of symmetry concept \\
    $\cdot$ is closed / closure: a \cdot b must be also in $G$ \\
    $\cdot$ is commutative: $x \cdot y = y \cdot x$ \\
    $\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
    $e$ is neutral element (identity) \\
    x-inverse (dual obj): $x \cdot x\inv = x\inv \cdot x = e$

** Ring-like structures

*** Semiring - Ring w/o additive inverse $\minus a$; Ring w/o i: R(i)ng
    
**** $R$ is commutative i.e. abelian monoid under addition:

     $+$ is associative:       $(a + b) + c = a + (b + c)$ \\
     $+$ is commutative:       $a + b = b + a$ \\
     $0$ is additive identity: $a + 0 = a$ \\
     Not required: additive inverse $a + (\minus a) = 0$, i.e. $\exists a \in R: \minus a \notin R$

**** $R$ is monoid under multiplication:

     $\cdot$ is associative:         $(a \cdot b) \cdot c = a \cdot (b \cdot c)$ \\
     $1$ is multiplicative identity: $a \cdot 1 = 1 \cdot a = a$

**** Multiplication is distributive with respect to addition:

     left distributivity:  $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$ \\
     right distributivity: $(b + c) \cdot a = (b \cdot a) + (c \cdot a)$

*** Near-ring
*** Commutative ring
*** Integral domain
*** Field (TODO is Field a ring-like structure, really?)
https://www.johndcook.com/blog/2017/03/26/visualizing-kinds-of-rings/
- Euclidean domain: Every field is a Euclidean domain.
- Principal Ideal Domain: Every Euclidean domain is a principal ideal domain (PID).
- Unique Factorization Domain Every principal ideal domain is a unique factorization domain (UFD).
- Domain: Every unique factorization domain is an integral domain.
- Integral Domain: A finite integral domain is a field.

*** Division ring
*** Ring $(R, +, \cdot)$ / Okruh

**** $R$ is commutative i.e. abelian group under addition:

     $+$ is associative:               $(a + b) + c = a + (b + c)$ \\
     $+$ is commutative:               $a + b = b + a$ \\
     $0$ is additive identity:         $a + 0 = a$ \\
     existence of an additive inverse: $\forall a \exists \minus a : a + (\minus a) = 0$

**** R is monoid under multiplication:

     $\cdot$ is associative:         $(a \cdot b) \cdot c = a \cdot (b \cdot c)$ \\
     $1$ is multiplicative identity: $a \cdot 1 = 1 \cdot a = a$

**** Multiplication is distributive with respect to addition:

     left distributivity:  $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$ \\
     right distributivity: $(b + c) \cdot a = (b \cdot a) + (c \cdot a)$

*** Ring theory

** Latice-like
*** Lattice
*** Semilattice
*** Complemented lattice
*** Total order
*** Heyting algebra
*** Boolean algebra
*** Map of lattices
*** Lattice theory

** Module-like
*** Module - A vector space with a ring of scalars
*** Group with operators
*** Vector space a.k.a linear space
* Socratica - What is a Vector Space? https://youtu.be/ozwodzD5bJM __ E.g.
* Vector - an arrow with a length and direction; Vector Space - collection of
vectors
* Subject of Linear algebra i.e. study of vector spaces
** Algebra-like
*** Algebra
*** Associative Non-associative Composition algebra
*** Lie algebra Graded Bialgebra

* Intuition: Category of X
*** Objects(X):
Elements  :
Structure :
Properties:
*** Morphisms(X):
Elements -> Elements; preserve structure

** Topological spaces: Top
Objects(Top)  : All Topological Spaces
Morphisms(Top): Continuous Maps

** Vector Spaces: Vec

*** Objects(Vec):
Elements : All Vector Spaces
Structure: add and scale vectors
Properties: adding vectors is commutative
*** Morphisms(Vec):
Linear transformations preserving sums and scalar multiplications - i.e. vector
scaling

** Posets: Pos
*** Objects(Pos)
Elements(Pos)  : Partialy ordered sets
Structure(Pos) : Order
Properties(Pos): Reflexivity, Transitivity
*** Morphisms(Pos): TODO
