#+LATEX: % generate pdf: M-x org-latex-export-to-pdf

#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{float}      % fixed table position
#+LATEX_HEADER: \usepackage{parskip}    % paragraphs
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}

* Hierarchy
What is needed to understand $X$? A big tree and paths through this tree.

Where leads understanding of $X_1, X_2, ..., X_n$? Prospects, applications in
other science fields, everyday life etc.

What's the next step? Why to study $Z$ and not $W$ after understanding $X_1,
X_2, ..., X_n$ in dependency of the field of some interest.

* Game Theory
Pure Strategy - set of decisions made with certitude. \\
Mixed Strategy - distribution of probabilities over some set of pure strategies.

** Nash Equilibrum
Each player gives best response to the others. Nobody has an incentive to
deviate from their actions if an equilibrum is played.

Example: Close windows to make air conditioning working: \\
Everybody just gives up without trying to convince others to close the window.

Example: Party organisation - follow the majority: \\
Majority joins - those skipping are penalized by "missed something". \\
Majority skips - those joining are penalized by "booring".

Nash Equilibrum TODOs:
1. Write action profiles for everyone (the matrix).
2. Calculate optimal mixed strategies for everyone in order to get Nash Equilibrum.
3. Calculate maxmin strategy and maxmin value (i.e. when the other guys do max harm to the i-th guy).

** Pareto Efficiency
Whenever all agents agree on ordering of outcomes the social welfare function
selects that ordering.

_Independence of Irrelevant Alternatives_: \\
If the selected ordering between two outcomes depends only on the relative
ordering they are given by the agents.

_Dictator_: \\
Single agent whose preferencies always determine the social ordering.

_Arrows Theorem_: \\
Any social welfare function that is pareto efficient and independent of
irrelevant alternatives is dictatorial.

** Markov chain (model)
[[https://youtu.be/o-jdJxXL_W4?t=423][Market transition]] \\
Dragan Djuric: Clojure on GPU \\
Bayadera (Bayesian): very fast \\
Bayesian is hard to compute, multi model, many dimensional problem, complex hyperspace \\
Markov Chain Monte Carlo simulations (MCMC): difficult to parallelize \\
JAGS/Stan (state-of-the-art bayesian C++ tools)

** Games beyond 2x2 (See the 2-4 Hardness lecture):
Linear Complementarity formulation\\
Support Enumeration Method

* Hypotheses, Conjectures & Theorems
** Goldbach conjencture
Every even integer $n \in \{2,4,6, ...\}$ is a sum of two primes.

** Riemann hypothesis
[[https://youtu.be/sD0NjbwqlYw][3Blue1Brown: Visualizing the Riemann hypothesis and analytic continuation]]

The real part of every non-trivial zero of the Zeta function $\zeta$ is $1/2$
(prime numbers).\\
_Or:_ \\
All the nontrivial zeroes of the analytic continuation of the Riemann zeta
function $\zeta$ have a real part equal to $1/2$.

** Poincare conjencture
Every simply connected, closed 3-manifold is homeomorfic to the 3-sphere
(Donuts)

** P vs. NP
Every problem whose solution can be quickly verified by a computer can also be
quickly solved by a computer.

** Fermant's Last Theorem
With $n,x,y,z \in \mathbb{N}$ and $n > 2$, the equation $x^n + y^n = z^n$ has no solutions.

** Continuum hypothesis
There is no set with cardinality strictly between the cardinalities of integers
and real numbers. Notes: R surj P(N) (Power series - Mocninovy rad)

** Fundamental Theorem of Arithmetics
Every positive integer $n \in \mathbb{N}$ can be written in a unique way as a
product of primes. \\
[[https://en.wikipedia.org/wiki/Barber_paradox][Barber paradox]] is derived from [[https://en.wikipedia.org/wiki/Russell%27s_paradox][Russell's paradox]].

* Probability
\begin{tabbing}
    Rule              \hspace{7em} \= Expression                                     \\
    Difference                     \> $P(B - A) = P(B) - P(A \cap B)$                \\
    Inclusion-Exclusion            \> $P(A \cup B) = P(A) + P(B) - P(A \cap B)$      \\
    Boole’s Inequality             \> $P(A \cup B) \Leftarrow P(A) + P(B)$           \\
    Monotonicity                   \> If $A \subseteq B$ then $P(A) \Leftarrow P(B)$ \\
\end{tabbing}

** Ordinary conditional probability $P(A \mid B) = P(A \cap B) / P(B)$
\begin{table}[H]
\begin{tabular}{|l|l|l|l|l|l|}
\hline
\multicolumn{2}{|l|}{Objective Health} & \multicolumn{2}{l|}{Test result} & Outcome                                   & Event $T \cap H$                                                       \\ \hline
ill / healthy & p           & i / h   & p       & probability                                                         & probability                                                            \\ \hline
$H$           & $P(H)$      & $T$     & $P(T)$  & \begin{tabular}[c]{@{}l@{}}$P(T \cap H) = P(H) \cdot P(T)$\end{tabular} & \begin{tabular}[c]{@{}l@{}}$P(T \mid H ) = P(T \cap H) / P(H)$\end{tabular} \\ \hline
really-i      & 0.1         & test-i  & 0.9     & 0.09                                                                & (/ 0.09 (+ 0.09 0.27))=0.25                                             \\ \hline
really-i      & 0.1         & test-h  & 0.1     & 0.01                                                                & (/ 0.01 (+ 0.01 0.63))=0.015625                                         \\ \hline
really-h      & 0.9         & test-i  & 0.3     & 0.27                                                                & (/ 0.27 (+ 0.09 0.27))=0.75                                             \\ \hline
really-h      & 0.9         & test-h  & 0.7     & 0.63                                                                & (/ 0.63 (+ 0.01 0.63))=0.984375                                         \\ \hline
\end{tabular}
\end{table}

- Generall test correctness: 0.09 + 0.63 = 0.72 (i.e. proper results for ill +
  proper results for healthy persons)
- Just guessing "everybody's healthy" gives 90% "generall test correctness"
  because the test is wrong only for ill patients and they make up 10% of the
  population.

#+NAME: <name>
#+BEGIN_SRC clojure
  #                      +-- test positive 0.9: 0.1 * 0.9 = 0.09
  #                      |
  #    +-----  ill 0.1 --+
  #    |                 |
  #    |                 +-- test negative 0.1: 0.1 * 0.1 = 0.01
  # ---+
  #    |                 +-- test positive 0.3: 0.9 * 0.3 = 0.27
  #    |                 |
  #    +-- healthy 0.9 --+
  #                      |
  #                      +-- test negative 0.7: 0.9 * 0.7 = 0.63
  ;; test is negative i.e. says "you're healthy" and the patient is really
  ;; ill (has the condition)
  (/ 0.01 (+ 0.01 0.63)) = 0.015625
  ;; test is positive i.e. says "you're ill" and the patient is really ill (has
  ;; the condition)
  (/ 0.09 (+ 0.09 0.27)) = 0.25
  ;; test is negative i.e. says "you're healthy" and the patient is really
  ;; health (doesn't have the condition)y
  (/ 0.63 (+ 0.01 0.63)) = 0.984375
  ;; test is posivite i.e. says "you're ill" and the patient is really
  ;; healthy (doesn't have the condition)
  (/ 0.27 (+ 0.09 0.27)) = 0.75
#+END_SRC
** A posteriori conditional probability
$$P(B \mid A) = P(A \cap B) / P(B)$$
If event $B$ precedes event $A$ in time. \\
Example: The probability it was cloudy this morning, given that it rained in the
afternoon.

* Homology
Higher dimensional analogues for studying loops = (alternative to) Homotopy
groups \\
Simplices: analogs of triangles in higher dimensions

* Fundamental group $\pi_2$ - loops of loops
Loops around sphere: captuers 2-dimensional hole in the sphere

$\pi_n$(S-k-upper-index) Homotopy group exists even if $n > k$; measuring higher
dimensional holes in k dimensional sphere

$\in$ is a containment relation

* Homotopy Type Theory
[[https://homotopytypetheory.org/][HoTT]] foundational framework; notions of paths in a space; equality and
quivalence.

Easier translation of mathematical proofs to a programming language of proof
assistants (than before).

** The Univalence Axiom
Identity is equivalent to equivalence, in particular: equivalent types are
identical.

For all types $A,B: \Pi A,B : Type.(A = B) \simeq (A \simeq B)$
- There's a function $UA: (A \simeq B) \rightarrow (A = B)$ such that from a
  proof equivalence of $A \simeq B$ it constructs a proof of equality $A = B$.
  Moreover a proof equivalence of $A \simeq B$ is equivalent to a proof of
  equality $A = B$. I.e. $(A \simeq B) \simeq (A = B)$.
- it allows to create a homotopy calculus w/o introduction of differential
  variety and even w/o an introduction of real numbers
Entier Relativ i.e. Set of Integers $\mathbb{Z}$.
