# generate pdf: M-x org-latex-export-to-pdf

#+LATEX_HEADER: \usepackage{cat-7-sketches}

# https://en.wikipedia.org/wiki/List_of_mathematical_symbols_by_subject
# latexpreview / nolatexpreview C-c C-x C-l
# #+STARTUP: nolatexpreview
#+STARTUP: showeverything inlineimages nolatexpreview

\href{http://math.chapman.edu/~jipsen/structures/doku.php}{Classes of math structures}

* Algebra

Algebra is a lot like arithmetic. In arithmetic the only unknown thing is the
answer to the problem. Algebra follows the rules of arithmetic. \\

Algebra uses operations of arithmetic: $+$, $-$, $*$, $/$ in equations: $1 + 2 = ...$ \\

Algebra adds the element of "unknown", typically a letter $x$ which is a
placeholder for some unknown value in the equation: $1 + 2 = x$ \\

Goals of algebra: what is the value of $x$? I.e. it's about "solving equations"

Abstract Algebra, aka Modern Algebra



* Algebraic structures
\href{https://en.wikipedia.org/wiki/Algebraic_structure}{Algebraic structure}
** Group-like structures
Group is a pair $(G, \cdot)$: \\
$G$ is an underlying body of an algebraic structure. Often it's a set. $\cdot$
is a binary operation. The element inversion $\blank^{-1}$ is apparently not
always being consider to be an operation.

| Group-like-Structure | Closed | Associative | Identity | Invertible | Commutative |
|----------------------+--------+-------------+----------+------------+-------------|
| Semigroupoid         | -      | Y           | -        | -          | -           |
| Small category       | -      | Y           | Y        | -          | -           |
| Groupoid             | -      | Y           | Y        | Y          | -           |
| Magma                | Y      | -           | -        | -          | -           |
| Quasigroup           | Y      | -           | -        | Y          | -           |
| Loop                 | Y      | -           | Y        | Y          | -           |
| Semigroup            | Y      | Y           | -        | -          | -           |
| Inverse semigroup    | Y      | Y           | -        | Y          | -           |
| Monoid               | Y      | Y           | Y        | -          | -           |
| Group                | Y      | Y           | Y        | Y          | -           |
| Abelian group        | Y      | Y           | Y        | Y          | Y           |

Closed / Closure property: all possible results of $a \cdot b$ are in the
underlying body \\
Associative, ie group with parentheses as you like, ie. no priority:
$a \cdot (b \cdot c) = (a \cdot b) \cdot c$ \\
Commutative, ie. order doesn't matter: $a \cdot b = b \cdot a$

\bigskip

Eg. for groups (which are associative, but not commutative): the priority of
operations doesn't exist bu the order of operands is important

*** Semigroup / Halbgruppe:
Semigroup is tuple $(G, \cdot)$ such that: \\
$\cdot$ is closed / closure: $a \cdot b$ must be also in $G$ \\
Not required: $\cdot$ is commutative: $x \cdot y = y \cdot x$ \\
$\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
Not required: $e$ is neutral element (identity) \\
Not required: $\blank\inv$ inversion (dual obj): $x \cdot x\inv = x\inv \cdot x = e$

*** Monoid
Monoid is a triple $(G, \cdot, e)$ such that: \\
A group without inverse elements. \\
$\cdot$ is closed / closure: $a \cdot b$ must be also in $G$ \\
$\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
$e$ is neutral element (identity) \\
Not required: $\blank\inv$ inversion (dual obj): $x \cdot x\inv = x\inv \cdot x = e$

*** Group
Group is a triple $(G, \cdot, e)$ such that: \\
A category w/ one object => every morphism is an isomorphism \\
$\cdot$ is closed / closure: $\forall a,b in G: a \cdot b$ must be also in $G$ \\
Not required: $\cdot$ is commutative: $x \cdot y = y \cdot x$ e.g. matrix
multiplication is not a commutative operation \\
$\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
$e$ is neutral element (identity) \\
$\blank\inv$ inversion (dual obj): $x \cdot x\inv = x\inv \cdot x = e$ \\

A category of /many/ morphisms and only /one/ object. All the morphisms are
invertible.

The pieces of the structure on $G$ can bee seen as maps of sets: \\
$\cdot : G^{2} \to G$ \\
$\blank\inv : G^{1} \to G$ \\
$e : G^{0} \to G$ \\

$G^{0}$ is the one-element set $1$ and we are using the observation that a map $1
\to G$ of sets is essentially the same thing as an element of $G$.


*** Normal Subgroups, Quotient (a.k.a Factor) Groups
Modular arithmetic done in the group theory by normal subgroups and quotient groups. \\
Congruence Classes $a \equiv b \pmod {n}$: $a$ is congruent to $b$ modulo $n$.
E.g. Integers under addition $+$ form a Group:\\
$0 + 3 \ZZ = \{... -6, -3, 0, 3, 6, ...\}$ - Normal Subgroup \\
$1 + 3 \ZZ = \{... -6, -3, 0, 3, 6, ...\}$ - Coset \\
$2 + 3 \ZZ = \{... -6, -3, 0, 3, 6, ...\}$ - Coset \\

A (Normal) Subgroup partitions a Group into (non-overlapping) Cosets. $0 + 3\ZZ$
is a Normal Subgroup and Cosets $1 + 3\ZZ$, $2 + 3\ZZ$ form a Quotient Group
$\ZZ / 3\ZZ$ a.k.a. a Factor Group. \\
_Notes_:
- the Quotient Group $\ZZ / 3\ZZ$ is not a Subgroup of $\ZZ$, i.e. $\ZZ / 3\ZZ
  \nleq \ZZ$. It is an entirely different group.
- in general the Cosets do not always form a Group.

*** Cyclic Group: generated by one element.

*** Commutative / Abelian group
Abelian group is a triple $(G, \cdot, e)$: elements with multiplication, such that: \\
Formalization of symmetry concept. \\
A symmetry of an object $G$ is a way of mapping $G$ to itself in a
reversible or invertible manner.\\
$\cdot$ is closed / closure: a \cdot b must be also in $G$ \\
$\cdot$ is commutative: $x \cdot y = y \cdot x$ \\
$\cdot$ is associative: $(x \cdot y) \cdot z = x \cdot (y \cdot z)$ \\
$e$ is neutral element (identity) \\
$\blank\inv$ inversion (dual obj): $x \cdot x\inv = x\inv \cdot x = e$

** Ring-like structures

*** Semiring - Ring w/o additive inverse $\minus a$; Ring w/o i: R(i)ng
- $R$ is commutative i.e. abelian monoid under addition:
  $+$ is associative:       $(a + b) + c = a + (b + c)$ \\
  $+$ is commutative:       $a + b = b + a$ \\
  $0$ is additive identity: $a + 0 = a$ \\
  Not required: additive inverse $a + (\minus a) = 0$, i.e. $\exists a \in R: \minus a \notin R$

- $R$ is monoid under multiplication:
  $\cdot$ is associative:         $(a \cdot b) \cdot c = a \cdot (b \cdot c)$ \\
  $1$ is multiplicative identity: $a \cdot 1 = 1 \cdot a = a$

- Multiplication is distributive with respect to addition:
  left distributivity:  $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$ \\
  right distributivity: $(b + c) \cdot a = (b \cdot a) + (c \cdot a)$

*** Near-ring
*** Commutative ring
*** Integral domain

*** Field
Field is a triple $(X, +, \minus)$ such that $X$ is an underlying set forming a
commutative, i.e. abelian group under the operations of: \\
  (commutative) addition: $a + b = b + a$ \\
  (commutative) multiplication: $a \times b = b \times a$, for non-zero elements
of $X$, to avoid division by $0$ \\
  addition and multiplication are distributive: $a \times (b + c) = a \times b +
a \times c$ \\

_Examples_: \\
$\CC$ Complex, $\RR$ Real and $\QQ$ Rational numbers form a Field. $\ZZ$ Integer
numbers don't form a Field. The $\ZZ$ don't have multiplicative inverses:
$$2\inv = \dfrac{1}{2} \notin \ZZ$$

\bigskip

TODO is Field a ring-like structure? I.e. does it have an associative
multiplication operation $\cdot$?

\bigskip

See
\href{https://www.johndcook.com/blog/2017/03/26/visualizing-kinds-of-rings/}{Visualizing kinds of rings}
- Euclidean domain: Every field is a Euclidean domain.
- Principal Ideal Domain: Every Euclidean domain is a principal ideal domain (PID).
- Unique Factorization Domain Every principal ideal domain is a unique factorization domain (UFD).
- Domain: Every unique factorization domain is an integral domain.
- Integral Domain: A finite integral domain is a field.

*** Division ring

*** Ring / Okruh
Ring is triple $(R, +, \cdot)$ such that: \\
- $R$ is commutative i.e. abelian group under addition: \\
  $+$ is associative:               $(a + b) + c = a + (b + c)$ \\
  $+$ is commutative:               $a + b = b + a$ \\
  $0$ is additive identity:         $a + 0 = a$ \\
  existence of an additive inverse: $\forall a \exists \minus a : a + (\minus a) = 0$

- $R$ is monoid under multiplication: \\
  $\cdot$ is associative:         $(a \cdot b) \cdot c = a \cdot (b \cdot c)$ \\
  $1$ is multiplicative identity: $a \cdot 1 = 1 \cdot a = a$

- Multiplication is distributive with respect to addition: \\
  left distributivity:  $a \cdot (b + c) = (a \cdot b) + (a \cdot c)$ \\
  right distributivity: $(b + c) \cdot a = (b \cdot a) + (c \cdot a)$

*** Ring theory

** Latice-like
*** Lattice
*** Semilattice
*** Complemented lattice
*** Total order
*** Heyting algebra
*** Boolean algebra
*** Map of lattices
*** Lattice theory

** Module-like
*** Group with operators

*** Vector space
Vector is quadruple $(V, +_v, F, +_f, \cdot, 1_f)$ such that: \\
- $V$ is an Abelian Group: $+_v$ is closed, commutative, associative, it has an
  identity and has invertible elements: $\forall v \in V \exists v\inv \in V$,
  and it contains a collection of vectors.
- $F$ is a Field of scalars.
- Operations and their properties:
    commutative vector addition: $v_1 +_v v_2 = v_2 +_v v_1$ \\
    vector scaling: $v \in V, f \in F: f \cdot v \in V$ \\
    distributivity of $\cdot$: $f \cdot (v_1 +_v v_2) = f \cdot v_1 +_f f \cdot v_2$,
    $(f_1 +_f f_2) \cdot v = f_1 \cdot v +_v f_2 \cdot v$ \\
    associativity of $\cdot$: $f_1 \cdot (f_2 \cdot v) = (f_1 \times \f_2) \cdot v$ \\
    scaling by $1_f$: $1_f \cdot v = v$

\bigskip

Vector space: \\
- \href{https://youtu.be/ozwodzD5bJM}{YouTube: Socratica - What is a Vector Space?}
- any type of mathematical object that can be multiplied by numbers and added
  together
- collection of vectors
- Linear algebra - study of vector spaces.

*** Module
Module is a generalization of a Vector Space.
A vector space with a ring of scalars.

** Algebra-like
*** Algebra
*** Associative Non-associative Composition algebra
*** Lie algebra Graded Bialgebra

* Intuition: Category of X
*** Objects(X):
Elements  :
Structure :
Properties:
*** Morphisms(X):
Elements -> Elements; preserve structure

** Topological spaces: Top
Objects(Top)  : All Topological Spaces
Morphisms(Top): Continuous Maps

** Vector Spaces: Vec

*** Objects(Vec):
Elements : All Vector Spaces
Structure: add and scale vectors
Properties: adding vectors is commutative
*** Morphisms(Vec):
Linear transformations preserving sums and scalar multiplications - i.e. vector
scaling

** Posets: Pos
*** Objects(Pos)
Elements(Pos)  : Partialy ordered sets
Structure(Pos) : Order
Properties(Pos): Reflexivity, Transitivity
*** Morphisms(Pos): TODO
