#+LATEX: % generate pdf: M-x org-latex-export-to-pdf

#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{float}      % fixed table position
#+LATEX_HEADER: \usepackage{parskip}    % paragraphs
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}   % unicode chars
#+LATEX_HEADER: \usepackage{minted}     % syntax coloring

\begin{minted}[style=solarized-dark]{clojure}
  (defn foo [] (println "foo"))
\end{minted}

\begin{minted}[style=solarized-dark]{bash}
  #!/usr/bin/bash
  for (( i=0; i != 10; i=i+1)); do
    echo $i
  done
\end{minted}


#+BEGIN_SRC emacs-lisp
  (message "Yeah from emacs-lisp!")
#+END_SRC

#+RESULTS:
: Yeah from emacs-lisp!

#+BEGIN_SRC sh :exports both
echo "Hello World from sh" # evaluate: C-c
#+END_SRC

#+RESULTS:
: Hello World from sh

#+begin_src clojure :results silent
;; ":results silent" causes result to be displayed in the mini-buffer
;; M-x cider-jack-in
(+ 1 4)
#+end_src

#+BEGIN_SRC clojure
(defproject my-project "0.1.0"
  :description "My great Clojure project"
  :dependencies
  [[org.clojure/clojure "1.9.0"]])
(println "Hello from clojure")
#+END_SRC

#+BEGIN_SRC python
# Result displayed under '#+RESULTS:'
return "Hello from Python" # evaluate: C-c
#+END_SRC

#+RESULTS:
: Hello from Python

#+RESULTS:
: Hello from python

* Brick-à-Brack
Solution of a Differential Equations (DE) is a function, not value \\
[[https://youtu.be/czL0ZSscbsM?t=II709][National Renewable Energy Laboratory: Energy-Cell Efficiencies]] \\
[[http://blog.sciencevsmagic.net/science/fractal-machine/][Fractals]] \\
Go over the book from the Prof. from Karlsruhe \\

Why Do Nigerian Scammers Say They are From Nigeria? \\
It works like a filter. If you believe them, you passed it. And you're likely
stupid enough to do anything they ask you for. IOW send them money. \\
If you don't pass it then it's probably not worth effort to flirt with you.

http://www.zdrojak.cz/clanky/tvorba-moderniho-e-shopu-dokonceni-uzivatelske-casti/
Sequence of QR Codes/ graphical elements (pyramide, cube, sphere, toroid, etc.)
Open Source Ecology: https://en.wikipedia.org/wiki/Open_Source_Ecology
Smart the collective brain http://www.ted.com/talks/matt_ridley_when_ideas_have_sex.html
time bank
dokaz identity bez udania mena
google lab tags http://www.chromeweblab.com/en-GB/lab-tag-explorer

Pure vs. mostly harmless functions

:terminals:
# A terminal for a more modern age
https://github.com/Eugeny/terminus

# electron-app terminal
https://github.com/zeit/hyper
:end:

:Lang:
http://www.ted.com/talks/patricia_kuhl_the_linguistic_genius_of_babies.html?fb_ref=talk
Learning pronounciation
How much of a language is silent? What does it look like when you take the silence out? (Video 2 Min)
http://www.theverge.com/2012/7/1/3129227/silenc-project-silent-letters
http://golancourses.net/ciid/19/silenc/
idioms, link sur FB, idioms - traduction + correcture
spelling glyphs
Comprehension - facile, s'exprimer - difficile
linguee.com - eu-texts
le Svejk, l'Etrangeur - examples
Communication w-/wo- Letters
:END:

* android
#+BEGIN_SRC fish
  exit 1 # just in case ...

  set cmd "ip address"
  eval $cmd
  #...

  set host $USER@<ip address>
  set src $host:/home/$USER
  $src/dev/navig/Osmand
  $src/dev/navig/osmand-api-demo

  rsync -azv gradle-4.6-bin.zip $src/dev/navig/osmand-api-demo/gradle/wrapper
  rsync -azv $src/.gradle ~/.gradle/
  rsync -azv $src/.m2 ~/.m2/

  # edit gradle-wrapper.properties
  distributionUrl=gradle-4.6-bin.zip

  inst android-sdk
  $HOME/Downloads/android
  # unzip and then
  tools/bin/sdkmanager --licenses
  sudo rsync -azv licenses/ $ANDROID_HOME/licenses/
  sudo chown -R $USER:$USER /usr/lib/android-sdk/
  rsync -azv $host:/usr/lib/android-sdk/ /usr/lib/
#+END_SRC

:org-mode-tagging:                                                      :org:
| col1    | col2          |
|---------+---------------|
| content | other content |
