#lang notes

@; any @include-section{...} is added at the end of the pdf file
@;@include-section{.scrbl}

@include-section{ai.scrbl}
@include-section{android.scrbl}
@include-section{ansible.scrbl}
@include-section{bric_a_brac.scrbl}
@include-section{chatGPT.scrbl}
@include-section{clojure_cljdocs.scrbl}
@include-section{clojure.scrbl}
@include-section{comp_sci_engineering.scrbl}
@include-section{comp_sci_theory.scrbl}
@include-section{cps.scrbl}
@include-section{crypto_mining.scrbl}
@include-section{crypto.scrbl}
@include-section{cvs.scrbl}
@include-section{db2.scrbl}
@include-section{dbases.scrbl}
@include-section{ddos.scrbl}
@include-section{drracket.scrbl}
@include-section{emacsconf2020.scrbl}
@include-section{emacs.scrbl}
@include-section{find_and_grep.scrbl}
@include-section{game.scrbl}
@include-section{git.scrbl}
@include-section{guile.scrbl}
@include-section{guile_scripting.scrbl}
@include-section{gui.scrbl}
@include-section{guix_home.scrbl}
@include-section{guix_package.scrbl}
@include-section{guix_pull_vs_upgrade.scrbl}
@include-section{guix_reproducible_environment.scrbl}
@include-section{guix.scrbl}
@include-section{guix_repl.scrbl}
@include-section{guix_system_configuration.scrbl}
@include-section{heroku.scrbl}
@include-section{influenza.scrbl}
@include-section{linux.scrbl}
@include-section{lisp.scrbl}
@include-section{listing.scrbl}
@include-section{logics.scrbl}
@include-section{mainframe_and_host.scrbl}
@include-section{make.scrbl}
@include-section{ms_windows.scrbl}
@include-section{mysql.scrbl}
@include-section{network.scrbl}
@include-section{nix.scrbl}
@include-section{node_js.scrbl}
@; @include-section{notes.scrbl} @; contains this definitions
@include-section{openssh.scrbl}
@include-section{org_mode.scrbl}
@include-section{packaging.scrbl}
@include-section{pandemics_data_sources.scrbl}
@include-section{pandemics_summary.scrbl}
@include-section{parsec.scrbl}
@include-section{postgresql.scrbl}
@include-section{racket_learning.scrbl}
@include-section{racket.scrbl}
@include-section{remove_guix_from_ubuntu.scrbl}
@include-section{rsync.scrbl}
@include-section{scheme_implementation.scrbl}
@include-section{shells.scrbl}
@include-section{systemd.scrbl}
@include-section{tex_and_latex.scrbl}
@include-section{thgtoa.scrbl}
@include-section{utf8.scrbl}
@include-section{vim.scrbl}
