:PROPERTIES:
:ID:       9a8f3716-5f95-4f28-bd60-b9f56bcefa1e
:END:
#+title: Pandemics Data Sources

* Current:
  https://ourworldindata.org/covid-vaccinations
  https://github.com/owid/covid-19-data/tree/master/public/data
  JHU: https://github.com/CSSEGISandData/COVID-19
** There really is just a single place collecting vaccination data:
   Our World in Data (University of Oxford): https://ourworldindata.org/covid-vaccinations
   Github Datasets: https://github.com/owid/covid-19-data/tree/master/public/data; https://github.com/owid

* ECDC= European Centre for Disease Prevention and Control (An agency of the European Union)
  https://www.ecdc.europa.eu/en/threats-and-outbreaks/epidemic-intelligence
  https://www.ecdc.europa.eu/en/covid-19/data
  Weekly Updates: https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases
  Official sources of the countries: https://www.ecdc.europa.eu/en/publications-data/sources-worldwide-data-covid-19

* USA Data: https://data.cdc.gov/Case-Surveillance/COVID-19-Case-Surveillance-Public-Use-Data/vbim-akqf

* WHO Datacollections:
** https://covid19.who.int/table
** WHO Global literature on coronavirus disease https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/
** Even the WHO uses Our World in Data:
   See https://covid19.who.int/info/
  "These data are pooled from numerous sources, including direct reports from
  Member States, WHO review of publicly available official data, or data
  collated and published by third-party sites such as Our World in Data. Data
  published by third-party sites have not been validated by WHO, and WHO cannot
  comment on accuracy or completeness. Differences in counts are expected
  compared to other sources due to different inclusion criteria and data cut-off
  times."

* RKI Data (down below on the page under "Daten zum Download"):
  https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html;jsessionid=4E2FFCBE1829A6C1DCA7622E496AA0E2.internet102?nn=2386228

* Open Access Data JHU: https://guides.library.jhu.edu/data-stats/covid19
  https://github.com/CSSEGISandData/COVID-19 (sources listed)

* Worldometers Data: https://www.worldometers.info/coronavirus/
** Listen jede Quelle jedes Landes (Seite Coronavirus unten)
** Erklärung wer/was: https://www.worldometers.info/coronavirus/about/Official
** Sources:
   reports, directly from Government's communication channels or indirectly,
   through local media sources when deemed reliable. We provide the source of
   each data update in the "Latest Updates" (News) section
** Daten nutzbar über Lizenzerwerb

* Open-Access Data and Computational Resources to Address COVID-19 (National Institute of Health USA) https://datascience.nih.gov/covid-19-open-access-resources
  davon nützlich:
** Data lake sample AWS: https://covid19-lake.s3.us-east-2.amazonaws.com/dashboard.html?dashboardName=COVID-19
   --> Beschränkter Zugriff, man braucht AWS-Konto:
   https://aws.amazon.com/de/blogs/big-data/a-public-data-lake-for-analysis-of-covid-19-data/;
   https://cord19.aws/
** US only Data: https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/
** International database of hCoV-19 genome sequences and related clinical and epidemiological data: https://www.gisaid.org/
** Data collection inkl. Quellcode: https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge
** The European COVID-19 Data Platform (interessant, aber keine neue Datenquelle): https://www.covid19dataportal.org/the-european-covid-19-data-platform
** Google cloud platform marketplace - Quellen/Datasets kaufen (kann aber Testphase nutzen): https://console.cloud.google.com/marketplace/browse?filter=solution-type:dataset&filter=category:covid19
** Die üblichen Datasources, wäre aber ein anderes API: https://outbreak.info/
** Webinar Sharing, Discovering and Citing COVID-19 Data and Code: https://datascience.nih.gov/repository-COVID-19-webinar inkl. Liste über Datenquelle
** Datensammlung auch zu anderen Krankheiten, aber die üblichen Quellen: https://nextstrain.org/
